#include "EditorLocalization.h"

#include <utility>

namespace ImWidgetV4Editor {

namespace {

constexpr const char* GEditorNamespacePrefix = "Editor.";

} // namespace

ImWidgetV4::FText EditorText(const std::string& key, const std::string& defaultText)
{
    return ImWidgetV4::FText::FromKey(std::string(GEditorNamespacePrefix) + key, defaultText);
}

void RegisterEditorDefaultStringTables()
{
    ImWidgetV4::FStringTable english;
    english.Culture = "en-US";
    english.Entries = {
        {"Editor.App.Title", "ImWidgetV4 Editor"},
        {"Editor.App.InitialHint", "Drag widgets from the left palette into the designer surface."},
        {"Editor.App.Action", "Action"},
        {"Editor.Common.Cancel", "Cancel"},
        {"Editor.Common.Close", "Close"},
        {"Editor.Common.Default", "Default"},
        {"Editor.Common.No", "No"},
        {"Editor.Common.None", "None"},
        {"Editor.Common.Yes", "Yes"},
        {"Editor.TitleBar.File", "File"},
        {"Editor.TitleBar.Edit", "Edit"},
        {"Editor.TitleBar.Project", "Project"},
        {"Editor.TitleBar.Build", "Build"},
        {"Editor.TitleBar.View", "View"},
        {"Editor.TitleBar.Search", "Search"},
        {"Editor.TitleBar.Undo", "Undo"},
        {"Editor.TitleBar.Redo", "Redo"},
        {"Editor.Language.English", "English"},
        {"Editor.Language.ChineseSimplified", "Chinese (Simplified)"},
        {"Editor.Dock.Controls", "Controls"},
        {"Editor.Dock.Project", "Project"},
        {"Editor.Dock.Build", "Build"},
        {"Editor.Dock.WidgetTree", "Widget Tree"},
        {"Editor.Workspace.Designer", "Designer"},
        {"Editor.Workspace.Preview", "Preview"},
        {"Editor.Workspace.Schema", "Schema"},
        {"Editor.Workspace.ProjectRoot", "Project root"},
        {"Editor.Workspace.SelectProjectRoot", "Select Project Root"},
        {"Editor.Workspace.SelectProjectRootFailed", "Select project root failed"},
        {"Editor.Workspace.SelectProjectRootUnsupported", "Select project root is unsupported by the active platform backend."},
        {"Editor.Build.NoProjectLoaded", "No project loaded."},
        {"Editor.Build.OverviewHint", "Build/Toolchain overview will appear here."},
        {"Editor.Build.PanelTitle", "Build"},
        {"Editor.Build.PanelBody", "Toolchain readiness, active profile, and recent build output."},
        {"Editor.Build.ActiveProfile", "Active Profile"},
        {"Editor.Build.Generator", "Generator"},
        {"Editor.Build.AndroidSdkRoot", "Android SDK Root"},
        {"Editor.Build.AndroidNdkRoot", "Android NDK Root"},
        {"Editor.Build.OverrideAndroidSdkRoot", "Override Android SDK root"},
        {"Editor.Build.OverrideAndroidNdkRoot", "Override Android NDK root"},
        {"Editor.Build.Apply", "Apply"},
        {"Editor.Build.Browse", "Browse"},
        {"Editor.Build.Build", "Build"},
        {"Editor.Build.BuildActiveProfile", "Build Active Profile"},
        {"Editor.Build.BuildFailedProfileNotFound", "Build failed: build profile not found."},
        {"Editor.Build.BuildFailedProjectRootNotConfigured", "Build failed: project root not configured."},
        {"Editor.Build.Complete", "complete"},
        {"Editor.Build.Clean", "Clean"},
        {"Editor.Build.CleanActiveProfile", "Clean Active Profile"},
        {"Editor.Build.CleanFailedProfileNotFound", "Clean failed: build profile not found."},
        {"Editor.Build.CleanFailedProjectRootNotConfigured", "Clean failed: project root not configured."},
        {"Editor.Build.Clear", "Clear"},
        {"Editor.Build.Checking", "Checking..."},
        {"Editor.Build.Configuration", "Configuration"},
        {"Editor.Build.Configure", "Configure"},
        {"Editor.Build.ConfigureActiveProfile", "Configure Active Profile"},
        {"Editor.Build.ConfigureFailedProfileNotFound", "Configure failed: build profile not found."},
        {"Editor.Build.ConfigureFailedProjectRootNotConfigured", "Configure failed: project root not configured."},
        {"Editor.Build.DirectoryNotAvailable", "Build directory not available"},
        {"Editor.Build.Directory", "Build Directory"},
        {"Editor.Build.Failed", "failed."},
        {"Editor.Build.FailedWithoutPeriod", "failed"},
        {"Editor.Build.Finished", "finished."},
        {"Editor.Build.Idle", "Idle"},
        {"Editor.Build.NeedsSetup", "Needs Setup"},
        {"Editor.Build.NoActiveBuildProfile", "No active build profile"},
        {"Editor.Build.NoProbeDataAvailable", "No probe data available."},
        {"Editor.Build.OpenOrCreateProjectHint", "Open or create an app project to inspect toolchain readiness."},
        {"Editor.Build.ProcessExitedWithCode", "Process exited with code"},
        {"Editor.Build.ProbeReady", "Probe Ready"},
        {"Editor.Build.Profile", "Profile"},
        {"Editor.Build.ProfileDetails", "Profile Details"},
        {"Editor.Build.Queued", "queued..."},
        {"Editor.Build.Ready", "Ready"},
        {"Editor.Build.Rebuild", "Rebuild"},
        {"Editor.Build.RebuildActiveProfile", "Rebuild Active Profile"},
        {"Editor.Build.RebuildFailedProfileNotFound", "Rebuild failed: build profile not found."},
        {"Editor.Build.RebuildFailedProjectRootNotConfigured", "Rebuild failed: project root not configured."},
        {"Editor.Build.Refreshing", "Refreshing"},
        {"Editor.Build.ReProbe", "Re-Probe"},
        {"Editor.Build.RequestIgnoredTaskRunning", "Build request ignored: another background build task is already running."},
        {"Editor.Build.Reveal", "Reveal"},
        {"Editor.Build.Running", "Running..."},
        {"Editor.Build.SaveActiveProfileFailed", "Failed to save active build profile"},
        {"Editor.Build.SaveProfileChangesFailed", "Failed to save build profile changes"},
        {"Editor.Build.NdkOverride", "NDK Override"},
        {"Editor.Build.RecentOutput", "Recent Output"},
        {"Editor.Build.RefreshingToolchainStatus", "Refreshing toolchain status..."},
        {"Editor.Build.SdkOverride", "SDK Override"},
        {"Editor.Build.Settings", "Settings"},
        {"Editor.Build.SetupNeeded", "Setup Needed"},
        {"Editor.Build.StartedInBackground", "started in background"},
        {"Editor.Build.Status", "Status"},
        {"Editor.Build.Unknown", "Unknown"},
        {"Editor.Build.Missing", "Missing"},
        {"Editor.Build.UseSettingsToUpdateProfile", "Use Settings to update this profile and re-probe."},
        {"Editor.Build.WorkflowUsesSavedProjectProfileSettings", "Build workflow uses saved project profile settings"},
        {"Editor.Output.Booting", "Booting editor session..."},
        {"Editor.Output.NoOpenDocuments", "No open documents."},
        {"Editor.Project.OpenDocuments", "Open Documents"},
        {"Editor.Project.NoOpenDocuments", "No open documents"},
        {"Editor.Project.RecentFiles", "Recent Files"},
        {"Editor.Project.NoRecentFiles", "No recent files"},
        {"Editor.Project.Workspace", "Workspace"},
        {"Editor.Project.WorkspaceRootNotConfigured", "Workspace root not configured"},
        {"Editor.Project.BuildProfiles", "Build Profiles"},
        {"Editor.Project.RefreshingEnvironmentProbe", "Refreshing environment probe..."},
        {"Editor.Project.ProbeDataUnavailable", "Probe data unavailable"},
        {"Editor.Project.NoSupportedFiles", "No supported files"},
        {"Editor.Project.AlreadyExists", "already exists."},
        {"Editor.Project.Create", "Create"},
        {"Editor.Project.CreateBlockedDirtyDocuments", "Create project blocked: save or discard dirty documents first."},
        {"Editor.Project.CreateDocumentFailed", "Create document failed"},
        {"Editor.Project.CreateDocumentFileNamePathSeparator", "Create document failed: file name must not contain path separators."},
        {"Editor.Project.CreateFolderFailed", "Create folder failed"},
        {"Editor.Project.CreateFolderFailedWithPeriod", "Create folder failed."},
        {"Editor.Project.CreateFolderNamePathSeparator", "Create folder failed: folder name must not contain path separators."},
        {"Editor.Project.CreateFolderSkippedAlreadyExists", "Create folder skipped"},
        {"Editor.Project.CreateFolderUnableToCreate", "Create folder failed: unable to create"},
        {"Editor.Project.CreateFolder", "Create Folder"},
        {"Editor.Project.CreateUIDocument", "Create UI Document"},
        {"Editor.Project.Created", "Created"},
        {"Editor.Project.CreatedFolder", "Created folder"},
        {"Editor.Project.DeleteBlockedDirtyDocuments", "Delete blocked: save or discard dirty documents under the selected path first."},
        {"Editor.Project.DeleteFailed", "Delete failed"},
        {"Editor.Project.DeleteFailedWithPeriod", "Delete failed."},
        {"Editor.Project.Deleted", "Deleted"},
        {"Editor.Project.ManifestLoadFailed", "Project manifest load failed"},
        {"Editor.Project.OpenFailed", "Open project failed"},
        {"Editor.Project.OpenBlockedDirtyDocuments", "Open project blocked: save or discard dirty documents first."},
        {"Editor.Project.OpenUnsupported", "Open project is unsupported by the active platform backend."},
        {"Editor.Project.OpenedAppProject", "Opened app project"},
        {"Editor.Project.OpenedStartupLoadFailed", "Project opened, but startup document could not be loaded."},
        {"Editor.Project.Rename", "Rename"},
        {"Editor.Project.RenameBlockedDirtyDocuments", "Rename blocked: save or discard dirty documents under the selected path first."},
        {"Editor.Project.RenameFailed", "Rename failed"},
        {"Editor.Project.RenameFailedWithPeriod", "Rename failed."},
        {"Editor.Project.RenameFile", "Rename File"},
        {"Editor.Project.RenameFolder", "Rename Folder"},
        {"Editor.Project.RenameNamePathSeparator", "Rename failed: name must not contain path separators."},
        {"Editor.Project.Renamed", "Renamed"},
        {"Editor.Project.RenameTargetExists", "Rename failed: target already exists."},
        {"Editor.Project.SelectAppProjectRoot", "Select App Project Root"},
        {"Editor.Project.SwitchedToAlreadyOpenDocument", "Switched to already open document"},
        {"Editor.Project.To", "to"},
        {"Editor.Menu.Activate", "Activate"},
        {"Editor.Menu.ActiveProfile", "Active Profile"},
        {"Editor.Menu.BuildThisProfile", "Build This Profile"},
        {"Editor.Menu.CleanThisProfile", "Clean This Profile"},
        {"Editor.Menu.CloseAll", "Close All"},
        {"Editor.Menu.CloseOthers", "Close Others"},
        {"Editor.Menu.ComingSoon", "Coming Soon"},
        {"Editor.Menu.ConfigureThisProfile", "Configure This Profile"},
        {"Editor.Menu.Copy", "Copy"},
        {"Editor.Menu.Cut", "Cut"},
        {"Editor.Menu.Delete", "Delete"},
        {"Editor.Menu.DeleteFile", "Delete File"},
        {"Editor.Menu.DeleteFolder", "Delete Folder"},
        {"Editor.Menu.DiscardChangesAndSwitch", "Discard Changes and Switch"},
        {"Editor.Menu.Duplicate", "Duplicate"},
        {"Editor.Menu.GenerateCpp", "Generate C++..."},
        {"Editor.Menu.Language", "Language"},
        {"Editor.Menu.New", "New"},
        {"Editor.Menu.NewAppProject", "New App Project..."},
        {"Editor.Menu.NewFolder", "New Folder"},
        {"Editor.Menu.NewUIDocument", "New UI Document..."},
        {"Editor.Menu.Open", "Open"},
        {"Editor.Menu.OpenAppProject", "Open App Project..."},
        {"Editor.Menu.OpenEllipsis", "Open..."},
        {"Editor.Menu.OpenProjectRoot", "Open Project Root..."},
        {"Editor.Menu.Paste", "Paste"},
        {"Editor.Menu.ProjectSettings", "Project Settings..."},
        {"Editor.Menu.RebuildThisProfile", "Rebuild This Profile"},
        {"Editor.Menu.RefreshProjectTree", "Refresh Project Tree"},
        {"Editor.Menu.RefreshThisFolder", "Refresh This Folder"},
        {"Editor.Menu.Rename", "Rename..."},
        {"Editor.Menu.RevealBuildFolder", "Reveal Build Folder"},
        {"Editor.Menu.RevealInFileManager", "Reveal in File Manager"},
        {"Editor.Menu.RevealProjectRoot", "Reveal Project Root"},
        {"Editor.Menu.Save", "Save"},
        {"Editor.Menu.SaveAs", "Save As..."},
        {"Editor.Menu.SaveAllAndSwitch", "Save All and Switch"},
        {"Editor.Menu.SetActiveProfile", "Set Active Profile"},
        {"Editor.Menu.SetAsProjectRoot", "Set As Project Root"},
        {"Editor.NewProject.ParentDirectory", "Parent Directory"},
        {"Editor.NewProject.CreateAppProject", "Create App Project"},
        {"Editor.NewProject.CreateFailed", "Create project failed"},
        {"Editor.NewProject.CreateFailedWithPeriod", "Create project failed."},
        {"Editor.NewProject.CreatedAppProject", "Created app project"},
        {"Editor.NewProject.InvalidMetadata", "Create project failed: invalid project metadata."},
        {"Editor.NewProject.NamespaceEmpty", "Create project failed: namespace must not be empty."},
        {"Editor.NewProject.ProjectName", "Project Name"},
        {"Editor.NewProject.ProjectNamePathSeparator", "Create project failed: project name must not contain path separators."},
        {"Editor.NewProject.Namespace", "Namespace"},
        {"Editor.NewProject.SelectParentDirectory", "Select New Project Parent Directory"},
        {"Editor.NewProject.StartupSessionCreateFailed", "Create project failed: could not create startup document session."},
        {"Editor.NewProject.StartupUI", "Startup UI"},
        {"Editor.NewProject.StartupUIPathSeparator", "Create project failed: startup UI name must not contain path separators."},
        {"Editor.NewProject.TargetFolderExists", "Create project failed: target folder already exists."},
        {"Editor.NewProject.Template", "Template"},
        {"Editor.NewProject.Unsupported", "Create project is unsupported by the active platform backend."},
        {"Editor.ProjectSettings.WindowsGenerator", "Windows Generator"},
        {"Editor.ProjectSettings.AndroidAbi", "Android ABI"},
        {"Editor.ProjectSettings.AndroidApiLevel", "Android API Level"},
        {"Editor.ProjectSettings.AndroidStl", "Android STL"},
        {"Editor.ProjectSettings.ActiveBuildProfile", "Active Build Profile"},
        {"Editor.ProjectSettings.EnvironmentProbe", "Environment Probe"},
        {"Editor.ProjectSettings.ProbeTarget", "Target"},
        {"Editor.ProjectSettings.ProbeReady", "Ready"},
        {"Editor.ProjectSettings.SelectBuildProfile", "Select a build profile."},
        {"Editor.ProjectSettings.SelectWindowsGenerator", "Select a Windows generator."},
        {"Editor.ProjectSettings.SelectValidWindowsGenerator", "Select a valid Windows generator."},
        {"Editor.ProjectSettings.SelectAndroidAbi", "Select an Android ABI."},
        {"Editor.ProjectSettings.SelectAndroidStl", "Select an Android STL."},
        {"Editor.ProjectSettings.AndroidApiLevelTooLow", "Android API Level must be 21 or higher."},
        {"Editor.ProjectSettings.SelectAndroidSdkRoot", "Select Android SDK Root"},
        {"Editor.ProjectSettings.SelectAndroidNdkRoot", "Select Android NDK Root"},
        {"Editor.ProjectSettings.FolderSelectionUnsupported", "Folder selection is unsupported by the active platform backend."},
        {"Editor.ProjectSettings.AndroidSdkRootSelectionFailed", "Android SDK root selection failed"},
        {"Editor.ProjectSettings.AndroidNdkRootSelectionFailed", "Android NDK root selection failed"},
        {"Editor.ProjectSettings.UnavailableNoActiveProject", "Project settings unavailable: no active project."},
        {"Editor.Details.Title", "Details"},
        {"Editor.Details.EmptyHint", "Select a widget in the designer surface to inspect its reflected properties."},
        {"Editor.Details.Common", "Common"},
        {"Editor.Details.Properties", "Properties"},
        {"Editor.Details.Slot", "Slot"},
        {"Editor.Details.Type", "Type"},
        {"Editor.Details.Name", "Name"},
        {"Editor.Details.Position", "Position"},
        {"Editor.Details.Size", "Size"},
        {"Editor.Details.Parent", "Parent"},
        {"Editor.Details.RootParent", "<root>"},
        {"Editor.Details.Unnamed", "<unnamed>"},
        {"Editor.Details.StructPlaceholder", "{...}"},
        {"Editor.Details.Unavailable", "<unavailable>"}
    };

    ImWidgetV4::FLocalizationManager::Get().RegisterStringTable(std::move(english));

    ImWidgetV4::FStringTable chinese;
    chinese.Culture = "zh-CN";
    chinese.Entries = {
        {"Editor.App.Title", "ImWidgetV4 编辑器"},
        {"Editor.App.InitialHint", "从左侧控件面板拖拽控件到设计画布。"},
        {"Editor.App.Action", "操作"},
        {"Editor.Common.Cancel", "取消"},
        {"Editor.Common.Close", "关闭"},
        {"Editor.Common.Default", "默认"},
        {"Editor.Common.No", "否"},
        {"Editor.Common.None", "无"},
        {"Editor.Common.Yes", "是"},
        {"Editor.TitleBar.File", "文件"},
        {"Editor.TitleBar.Edit", "编辑"},
        {"Editor.TitleBar.Project", "项目"},
        {"Editor.TitleBar.Build", "构建"},
        {"Editor.TitleBar.View", "视图"},
        {"Editor.TitleBar.Search", "搜索"},
        {"Editor.TitleBar.Undo", "撤销"},
        {"Editor.TitleBar.Redo", "重做"},
        {"Editor.Language.English", "English"},
        {"Editor.Language.ChineseSimplified", "简体中文"},
        {"Editor.Dock.Controls", "控件"},
        {"Editor.Dock.Project", "项目"},
        {"Editor.Dock.Build", "构建"},
        {"Editor.Dock.WidgetTree", "控件树"},
        {"Editor.Workspace.Designer", "设计器"},
        {"Editor.Workspace.Preview", "预览"},
        {"Editor.Workspace.Schema", "Schema"},
        {"Editor.Workspace.ProjectRoot", "项目根目录"},
        {"Editor.Workspace.SelectProjectRoot", "选择项目根目录"},
        {"Editor.Workspace.SelectProjectRootFailed", "选择项目根目录失败"},
        {"Editor.Workspace.SelectProjectRootUnsupported", "当前平台后端不支持选择项目根目录。"},
        {"Editor.Build.NoProjectLoaded", "未加载项目。"},
        {"Editor.Build.OverviewHint", "构建/工具链概览将显示在这里。"},
        {"Editor.Build.PanelTitle", "构建"},
        {"Editor.Build.PanelBody", "工具链状态、当前配置和最近构建输出。"},
        {"Editor.Build.ActiveProfile", "当前配置"},
        {"Editor.Build.Generator", "生成器"},
        {"Editor.Build.AndroidSdkRoot", "Android SDK 根目录"},
        {"Editor.Build.AndroidNdkRoot", "Android NDK 根目录"},
        {"Editor.Build.OverrideAndroidSdkRoot", "覆盖 Android SDK 根目录"},
        {"Editor.Build.OverrideAndroidNdkRoot", "覆盖 Android NDK 根目录"},
        {"Editor.Build.Apply", "应用"},
        {"Editor.Build.Browse", "浏览"},
        {"Editor.Build.Build", "构建"},
        {"Editor.Build.BuildActiveProfile", "构建当前配置"},
        {"Editor.Build.BuildFailedProfileNotFound", "构建失败：未找到构建配置。"},
        {"Editor.Build.BuildFailedProjectRootNotConfigured", "构建失败：尚未配置项目根目录。"},
        {"Editor.Build.Complete", "完成"},
        {"Editor.Build.Clean", "清理"},
        {"Editor.Build.CleanActiveProfile", "清理当前配置"},
        {"Editor.Build.CleanFailedProfileNotFound", "清理失败：未找到构建配置。"},
        {"Editor.Build.CleanFailedProjectRootNotConfigured", "清理失败：尚未配置项目根目录。"},
        {"Editor.Build.Clear", "清除"},
        {"Editor.Build.Checking", "检查中..."},
        {"Editor.Build.Configuration", "配置"},
        {"Editor.Build.Configure", "配置"},
        {"Editor.Build.ConfigureActiveProfile", "配置当前配置"},
        {"Editor.Build.ConfigureFailedProfileNotFound", "配置失败：未找到构建配置。"},
        {"Editor.Build.ConfigureFailedProjectRootNotConfigured", "配置失败：尚未配置项目根目录。"},
        {"Editor.Build.DirectoryNotAvailable", "构建目录不可用"},
        {"Editor.Build.Directory", "构建目录"},
        {"Editor.Build.Failed", "失败。"},
        {"Editor.Build.FailedWithoutPeriod", "失败"},
        {"Editor.Build.Finished", "完成。"},
        {"Editor.Build.Idle", "空闲"},
        {"Editor.Build.NeedsSetup", "需要设置"},
        {"Editor.Build.NoActiveBuildProfile", "没有当前构建配置"},
        {"Editor.Build.NoProbeDataAvailable", "没有可用的探测数据。"},
        {"Editor.Build.OpenOrCreateProjectHint", "打开或创建应用项目以检查工具链就绪状态。"},
        {"Editor.Build.ProcessExitedWithCode", "进程退出码"},
        {"Editor.Build.ProbeReady", "探测就绪"},
        {"Editor.Build.Profile", "配置"},
        {"Editor.Build.ProfileDetails", "配置详情"},
        {"Editor.Build.Queued", "已排队..."},
        {"Editor.Build.Ready", "就绪"},
        {"Editor.Build.Rebuild", "重新构建"},
        {"Editor.Build.RebuildActiveProfile", "重新构建当前配置"},
        {"Editor.Build.RebuildFailedProfileNotFound", "重新构建失败：未找到构建配置。"},
        {"Editor.Build.RebuildFailedProjectRootNotConfigured", "重新构建失败：尚未配置项目根目录。"},
        {"Editor.Build.Refreshing", "刷新中"},
        {"Editor.Build.ReProbe", "重新探测"},
        {"Editor.Build.RequestIgnoredTaskRunning", "构建请求已忽略：已有后台构建任务正在运行。"},
        {"Editor.Build.Reveal", "显示"},
        {"Editor.Build.Running", "运行中..."},
        {"Editor.Build.SaveActiveProfileFailed", "保存当前构建配置失败"},
        {"Editor.Build.SaveProfileChangesFailed", "保存构建配置更改失败"},
        {"Editor.Build.NdkOverride", "NDK 覆盖"},
        {"Editor.Build.RecentOutput", "最近输出"},
        {"Editor.Build.RefreshingToolchainStatus", "正在刷新工具链状态..."},
        {"Editor.Build.SdkOverride", "SDK 覆盖"},
        {"Editor.Build.Settings", "设置"},
        {"Editor.Build.SetupNeeded", "需要设置"},
        {"Editor.Build.StartedInBackground", "已在后台启动"},
        {"Editor.Build.Status", "状态"},
        {"Editor.Build.Unknown", "未知"},
        {"Editor.Build.Missing", "缺少"},
        {"Editor.Build.UseSettingsToUpdateProfile", "使用设置更新此配置并重新探测。"},
        {"Editor.Build.WorkflowUsesSavedProjectProfileSettings", "构建流程使用已保存的项目配置设置"},
        {"Editor.Output.Booting", "正在启动编辑器会话..."},
        {"Editor.Output.NoOpenDocuments", "没有打开的文档。"},
        {"Editor.Project.OpenDocuments", "打开的文档"},
        {"Editor.Project.NoOpenDocuments", "没有打开的文档"},
        {"Editor.Project.RecentFiles", "最近文件"},
        {"Editor.Project.NoRecentFiles", "没有最近文件"},
        {"Editor.Project.Workspace", "工作区"},
        {"Editor.Project.WorkspaceRootNotConfigured", "尚未配置工作区根目录"},
        {"Editor.Project.BuildProfiles", "构建配置"},
        {"Editor.Project.RefreshingEnvironmentProbe", "正在刷新环境探测..."},
        {"Editor.Project.ProbeDataUnavailable", "探测数据不可用"},
        {"Editor.Project.NoSupportedFiles", "没有支持的文件"},
        {"Editor.Project.AlreadyExists", "已存在。"},
        {"Editor.Project.CreateBlockedDirtyDocuments", "创建项目已阻止：请先保存或放弃未保存的文档。"},
        {"Editor.Project.CreateDocumentFailed", "创建文档失败"},
        {"Editor.Project.CreateDocumentFileNamePathSeparator", "创建文档失败：文件名不能包含路径分隔符。"},
        {"Editor.Project.CreateFolderFailed", "创建文件夹失败"},
        {"Editor.Project.CreateFolderFailedWithPeriod", "创建文件夹失败。"},
        {"Editor.Project.CreateFolderNamePathSeparator", "创建文件夹失败：文件夹名不能包含路径分隔符。"},
        {"Editor.Project.CreateFolderSkippedAlreadyExists", "已跳过创建文件夹"},
        {"Editor.Project.CreateFolderUnableToCreate", "创建文件夹失败：无法创建"},
        {"Editor.Project.Create", "创建"},
        {"Editor.Project.CreateFolder", "创建文件夹"},
        {"Editor.Project.CreateUIDocument", "创建 UI 文档"},
        {"Editor.Project.Created", "已创建"},
        {"Editor.Project.CreatedFolder", "已创建文件夹"},
        {"Editor.Project.DeleteBlockedDirtyDocuments", "删除已阻止：请先保存或放弃所选路径下未保存的文档。"},
        {"Editor.Project.DeleteFailed", "删除失败"},
        {"Editor.Project.DeleteFailedWithPeriod", "删除失败。"},
        {"Editor.Project.Deleted", "已删除"},
        {"Editor.Project.ManifestLoadFailed", "项目清单加载失败"},
        {"Editor.Project.OpenFailed", "打开项目失败"},
        {"Editor.Project.OpenBlockedDirtyDocuments", "打开项目已阻止：请先保存或放弃未保存的文档。"},
        {"Editor.Project.OpenUnsupported", "当前平台后端不支持打开项目。"},
        {"Editor.Project.OpenedAppProject", "已打开应用项目"},
        {"Editor.Project.OpenedStartupLoadFailed", "项目已打开，但无法加载启动文档。"},
        {"Editor.Project.Rename", "重命名"},
        {"Editor.Project.RenameBlockedDirtyDocuments", "重命名已阻止：请先保存或放弃所选路径下未保存的文档。"},
        {"Editor.Project.RenameFailed", "重命名失败"},
        {"Editor.Project.RenameFailedWithPeriod", "重命名失败。"},
        {"Editor.Project.RenameFile", "重命名文件"},
        {"Editor.Project.RenameFolder", "重命名文件夹"},
        {"Editor.Project.RenameNamePathSeparator", "重命名失败：名称不能包含路径分隔符。"},
        {"Editor.Project.Renamed", "已重命名"},
        {"Editor.Project.RenameTargetExists", "重命名失败：目标已存在。"},
        {"Editor.Project.SelectAppProjectRoot", "选择应用项目根目录"},
        {"Editor.Project.SwitchedToAlreadyOpenDocument", "已切换到打开的文档"},
        {"Editor.Project.To", "为"},
        {"Editor.Menu.Activate", "激活"},
        {"Editor.Menu.ActiveProfile", "当前配置"},
        {"Editor.Menu.BuildThisProfile", "构建此配置"},
        {"Editor.Menu.CleanThisProfile", "清理此配置"},
        {"Editor.Menu.CloseAll", "全部关闭"},
        {"Editor.Menu.CloseOthers", "关闭其他"},
        {"Editor.Menu.ComingSoon", "即将推出"},
        {"Editor.Menu.ConfigureThisProfile", "配置此配置"},
        {"Editor.Menu.Copy", "复制"},
        {"Editor.Menu.Cut", "剪切"},
        {"Editor.Menu.Delete", "删除"},
        {"Editor.Menu.DeleteFile", "删除文件"},
        {"Editor.Menu.DeleteFolder", "删除文件夹"},
        {"Editor.Menu.DiscardChangesAndSwitch", "放弃更改并切换"},
        {"Editor.Menu.Duplicate", "复制控件"},
        {"Editor.Menu.GenerateCpp", "生成 C++..."},
        {"Editor.Menu.Language", "语言"},
        {"Editor.Menu.New", "新建"},
        {"Editor.Menu.NewAppProject", "新建应用项目..."},
        {"Editor.Menu.NewFolder", "新建文件夹"},
        {"Editor.Menu.NewUIDocument", "新建 UI 文档..."},
        {"Editor.Menu.Open", "打开"},
        {"Editor.Menu.OpenAppProject", "打开应用项目..."},
        {"Editor.Menu.OpenEllipsis", "打开..."},
        {"Editor.Menu.OpenProjectRoot", "打开项目根目录..."},
        {"Editor.Menu.Paste", "粘贴"},
        {"Editor.Menu.ProjectSettings", "项目设置..."},
        {"Editor.Menu.RebuildThisProfile", "重新构建此配置"},
        {"Editor.Menu.RefreshProjectTree", "刷新项目树"},
        {"Editor.Menu.RefreshThisFolder", "刷新此文件夹"},
        {"Editor.Menu.Rename", "重命名..."},
        {"Editor.Menu.RevealBuildFolder", "显示构建目录"},
        {"Editor.Menu.RevealInFileManager", "在文件管理器中显示"},
        {"Editor.Menu.RevealProjectRoot", "显示项目根目录"},
        {"Editor.Menu.Save", "保存"},
        {"Editor.Menu.SaveAs", "另存为..."},
        {"Editor.Menu.SaveAllAndSwitch", "全部保存并切换"},
        {"Editor.Menu.SetActiveProfile", "设为当前配置"},
        {"Editor.Menu.SetAsProjectRoot", "设为项目根目录"},
        {"Editor.NewProject.ParentDirectory", "父目录"},
        {"Editor.NewProject.CreateAppProject", "创建应用项目"},
        {"Editor.NewProject.CreateFailed", "创建项目失败"},
        {"Editor.NewProject.CreateFailedWithPeriod", "创建项目失败。"},
        {"Editor.NewProject.CreatedAppProject", "已创建应用项目"},
        {"Editor.NewProject.InvalidMetadata", "创建项目失败：项目元数据无效。"},
        {"Editor.NewProject.NamespaceEmpty", "创建项目失败：命名空间不能为空。"},
        {"Editor.NewProject.ProjectName", "项目名称"},
        {"Editor.NewProject.ProjectNamePathSeparator", "创建项目失败：项目名称不能包含路径分隔符。"},
        {"Editor.NewProject.Namespace", "命名空间"},
        {"Editor.NewProject.SelectParentDirectory", "选择新项目父目录"},
        {"Editor.NewProject.StartupSessionCreateFailed", "创建项目失败：无法创建启动文档会话。"},
        {"Editor.NewProject.StartupUI", "启动 UI"},
        {"Editor.NewProject.StartupUIPathSeparator", "创建项目失败：启动 UI 名称不能包含路径分隔符。"},
        {"Editor.NewProject.TargetFolderExists", "创建项目失败：目标文件夹已存在。"},
        {"Editor.NewProject.Template", "模板"},
        {"Editor.NewProject.Unsupported", "当前平台后端不支持创建项目。"},
        {"Editor.ProjectSettings.WindowsGenerator", "Windows 生成器"},
        {"Editor.ProjectSettings.AndroidAbi", "Android ABI"},
        {"Editor.ProjectSettings.AndroidApiLevel", "Android API 级别"},
        {"Editor.ProjectSettings.AndroidStl", "Android STL"},
        {"Editor.ProjectSettings.ActiveBuildProfile", "当前构建配置"},
        {"Editor.ProjectSettings.EnvironmentProbe", "环境探测"},
        {"Editor.ProjectSettings.ProbeTarget", "目标"},
        {"Editor.ProjectSettings.ProbeReady", "就绪"},
        {"Editor.ProjectSettings.SelectBuildProfile", "请选择构建配置。"},
        {"Editor.ProjectSettings.SelectWindowsGenerator", "请选择 Windows 生成器。"},
        {"Editor.ProjectSettings.SelectValidWindowsGenerator", "请选择有效的 Windows 生成器。"},
        {"Editor.ProjectSettings.SelectAndroidAbi", "请选择 Android ABI。"},
        {"Editor.ProjectSettings.SelectAndroidStl", "请选择 Android STL。"},
        {"Editor.ProjectSettings.AndroidApiLevelTooLow", "Android API 级别必须大于等于 21。"},
        {"Editor.ProjectSettings.SelectAndroidSdkRoot", "选择 Android SDK 根目录"},
        {"Editor.ProjectSettings.SelectAndroidNdkRoot", "选择 Android NDK 根目录"},
        {"Editor.ProjectSettings.FolderSelectionUnsupported", "当前平台后端不支持选择文件夹。"},
        {"Editor.ProjectSettings.AndroidSdkRootSelectionFailed", "Android SDK 根目录选择失败"},
        {"Editor.ProjectSettings.AndroidNdkRootSelectionFailed", "Android NDK 根目录选择失败"},
        {"Editor.ProjectSettings.UnavailableNoActiveProject", "项目设置不可用：没有活动项目。"},
        {"Editor.Details.Title", "详情"},
        {"Editor.Details.EmptyHint", "在设计画布中选择控件以检查其反射属性。"},
        {"Editor.Details.Common", "通用"},
        {"Editor.Details.Properties", "属性"},
        {"Editor.Details.Slot", "Slot"},
        {"Editor.Details.Type", "类型"},
        {"Editor.Details.Name", "名称"},
        {"Editor.Details.Position", "位置"},
        {"Editor.Details.Size", "尺寸"},
        {"Editor.Details.Parent", "父级"},
        {"Editor.Details.RootParent", "<根>"},
        {"Editor.Details.Unnamed", "<未命名>"},
        {"Editor.Details.StructPlaceholder", "{...}"},
        {"Editor.Details.Unavailable", "<不可用>"}
    };

    ImWidgetV4::FLocalizationManager::Get().RegisterStringTable(std::move(chinese));
}

} // namespace ImWidgetV4Editor
