#include "ProjectScaffolder.h"

#include "../codegen/WidgetTreeToCppGenerator.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>

namespace ImWidgetV4Editor {

namespace {

std::string BuildStringLiteral(const std::string& value)
{
    std::string result = "\"";
    result.reserve(value.size() + 8);

    for (char c : value) {
        switch (c) {
        case '\\':
            result += "\\\\";
            break;
        case '\"':
            result += "\\\"";
            break;
        case '\n':
            result += "\\n";
            break;
        case '\r':
            result += "\\r";
            break;
        case '\t':
            result += "\\t";
            break;
        default:
            result.push_back(c);
            break;
        }
    }

    result.push_back('\"');
    return result;
}

std::string BuildPathLiteral(const std::filesystem::path& value)
{
    return BuildStringLiteral(value.generic_string());
}

bool IsIdentifierStartChar(char c)
{
    const unsigned char value = static_cast<unsigned char>(c);
    return std::isalpha(value) != 0 || c == '_';
}

bool IsIdentifierContinueChar(char c)
{
    const unsigned char value = static_cast<unsigned char>(c);
    return std::isalnum(value) != 0 || c == '_';
}

std::string NormalizeIdentifier(const std::string& rawText, const std::string& fallback)
{
    auto sanitize = [](const std::string& text) {
        std::string result;
        result.reserve(text.size());
        for (char c : text) {
            if (IsIdentifierContinueChar(c)) {
                result.push_back(c);
            } else if (result.empty() || result.back() != '_') {
                result.push_back('_');
            }
        }

        while (!result.empty() && result.back() == '_') {
            result.pop_back();
        }

        return result;
    };

    std::string normalized = sanitize(rawText);
    if (normalized.empty()) {
        normalized = sanitize(fallback);
    }
    if (normalized.empty()) {
        normalized = "ImWidgetApp";
    }
    if (!IsIdentifierStartChar(normalized.front())) {
        normalized.insert(normalized.begin(), '_');
    }
    return normalized;
}

bool WriteTextFile(
    const std::filesystem::path& filePath,
    const std::string& text,
    std::string& outError)
{
    try {
        const std::filesystem::path parentPath = filePath.parent_path();
        if (!parentPath.empty()) {
            std::filesystem::create_directories(parentPath);
        }

        std::ofstream stream(filePath, std::ios::binary | std::ios::trunc);
        if (!stream.is_open()) {
            outError = "Failed to open " + filePath.string() + " for writing.";
            return false;
        }

        stream << text;
        stream.flush();
        if (!stream.good()) {
            outError = "Failed to write " + filePath.string() + ".";
            return false;
        }

        return true;
    } catch (const std::exception& exception) {
        outError = exception.what();
        return false;
    } catch (...) {
        outError = "Unknown file write error.";
        return false;
    }
}

std::string BuildRootCMakeListsText(
    const FProjectScaffoldRequest& request,
    const std::string& cmakeProjectName)
{
    std::ostringstream stream;
    stream
        << "cmake_minimum_required(VERSION 3.15)\n"
        << "project(" << cmakeProjectName << " LANGUAGES CXX)\n\n"
        << "# User-owned entry point. The editor creates this file once and does not\n"
        << "# overwrite it during project code regeneration.\n"
        << "include(cmake/ImWidgetV4GeneratedProject.cmake)\n\n"
        << "if(EXISTS \"${CMAKE_CURRENT_SOURCE_DIR}/cmake/UserProject.cmake\")\n"
        << "    include(cmake/UserProject.cmake)\n"
        << "endif()\n";
    return stream.str();
}

std::string BuildUserProjectCMakeText()
{
    std::ostringstream stream;
    stream
        << "# User-owned CMake extension file.\n"
        << "# Add your own sources, include directories, compile definitions, libraries,\n"
        << "# resources, or target properties here. The editor never overwrites this file.\n"
        << "#\n"
        << "# Example:\n"
        << "# target_sources(${PROJECT_NAME} PRIVATE src/MyFeature.cpp)\n"
        << "# target_compile_definitions(${PROJECT_NAME} PRIVATE MY_FEATURE=1)\n";
    return stream.str();
}

std::string BuildGeneratedProjectCMakeText(
    const FProjectScaffoldRequest& request)
{
    std::ostringstream stream;
    stream
        << "# Auto-generated by ImWidgetV4Editor. Do not edit manually.\n"
        << "# Use cmake/UserProject.cmake for user CMake customizations.\n\n"
        << "set(CMAKE_CXX_STANDARD 17)\n"
        << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        << "set(CMAKE_CXX_EXTENSIONS OFF)\n\n"
        << "set(IMWIDGETV4_ROOT \"\" CACHE PATH \"Path to the ImWidgetV4 library root\")\n"
        << "if(IMWIDGETV4_ROOT STREQUAL \"\")\n"
        << "    get_filename_component(IMWIDGETV4_ROOT \"${CMAKE_CURRENT_SOURCE_DIR}/../ImWidgetV4\" ABSOLUTE)\n"
        << "endif()\n\n"
        << "if(NOT EXISTS \"${IMWIDGETV4_ROOT}/CMakeLists.txt\")\n"
        << "    message(FATAL_ERROR \"IMWIDGETV4_ROOT must point to the ImWidgetV4 library root.\")\n"
        << "endif()\n\n"
        << "set(IMWIDGETV4_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)\n"
        << "set(IMWIDGETV4_BUILD_SAMPLES OFF CACHE BOOL \"\" FORCE)\n"
        << "set(IMWIDGETV4_BUILD_EDITOR OFF CACHE BOOL \"\" FORCE)\n"
        << "if(WIN32)\n"
        << "    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND ON CACHE BOOL \"\" FORCE)\n"
        << "    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND OFF CACHE BOOL \"\" FORCE)\n"
        << "elseif(ANDROID)\n"
        << "    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND OFF CACHE BOOL \"\" FORCE)\n"
        << "    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND ON CACHE BOOL \"\" FORCE)\n"
        << "else()\n"
        << "    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND OFF CACHE BOOL \"\" FORCE)\n"
        << "    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND OFF CACHE BOOL \"\" FORCE)\n"
        << "endif()\n\n"
        << "add_subdirectory(\"${IMWIDGETV4_ROOT}\" \"${CMAKE_BINARY_DIR}/ImWidgetV4\")\n\n"
        << "set(IMWIDGETV4_APP_SOURCES\n"
        << "    src/main.cpp\n"
        << "    generated/AppProjectConfig.cpp\n"
        << "    generated/" << request.StartupWidgetClassName << ".cpp\n";
    if (request.TitleBarRootWidget) {
        stream
            << "    generated/" << request.TitleBarWidgetClassName << ".cpp\n";
    }
    stream
        << ")\n\n"
        << "if(ANDROID)\n"
        << "    set(IMWIDGETV4_ANDROID_NDK_ROOT \"\")\n"
        << "    if(DEFINED CMAKE_ANDROID_NDK)\n"
        << "        set(IMWIDGETV4_ANDROID_NDK_ROOT ${CMAKE_ANDROID_NDK})\n"
        << "    elseif(DEFINED ANDROID_NDK)\n"
        << "        set(IMWIDGETV4_ANDROID_NDK_ROOT ${ANDROID_NDK})\n"
        << "    endif()\n\n"
        << "    set(IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE \"\")\n"
        << "    if(IMWIDGETV4_ANDROID_NDK_ROOT)\n"
        << "        set(IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE\n"
        << "            ${IMWIDGETV4_ANDROID_NDK_ROOT}/sources/android/native_app_glue/android_native_app_glue.c\n"
        << "        )\n"
        << "    endif()\n\n"
        << "    add_library(${PROJECT_NAME} SHARED\n"
        << "        ${IMWIDGETV4_APP_SOURCES}\n"
        << "        ${IMWIDGETV4_ROOT}/src/app/AndroidHostedMain.cpp\n"
        << "        ${IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE}\n"
        << "    )\n"
        << "else()\n"
        << "    add_executable(${PROJECT_NAME}\n"
        << "        ${IMWIDGETV4_APP_SOURCES}\n"
        << "        ${IMWIDGETV4_ROOT}/src/app/Win32HostedMain.cpp\n"
        << "    )\n"
        << "endif()\n\n"
        << "target_include_directories(${PROJECT_NAME} PRIVATE\n"
        << "    ${CMAKE_CURRENT_SOURCE_DIR}/generated\n"
        << ")\n\n"
        << "target_link_libraries(${PROJECT_NAME} PRIVATE\n"
        << "    imwidgetv4_core\n"
        << ")\n\n"
        << "if(WIN32)\n"
        << "    target_link_libraries(${PROJECT_NAME} PRIVATE imwidgetv4_platform_win32_dx11)\n"
        << "    set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE TRUE)\n"
        << "elseif(ANDROID)\n"
        << "    target_link_libraries(${PROJECT_NAME} PRIVATE\n"
        << "        imwidgetv4_platform_android_gles3\n"
        << "        android\n"
        << "        log\n"
        << "    )\n"
        << "    if(IMWIDGETV4_ANDROID_NDK_ROOT)\n"
        << "        target_include_directories(${PROJECT_NAME} PRIVATE\n"
        << "            ${IMWIDGETV4_ANDROID_NDK_ROOT}/sources/android/native_app_glue\n"
        << "        )\n"
        << "    endif()\n"
        << "else()\n"
        << "    message(FATAL_ERROR \"Generated project supports only WIN32 or ANDROID hosts.\")\n"
        << "endif()\n\n"
        << "if(MSVC)\n"
        << "    target_compile_options(${PROJECT_NAME} PRIVATE /utf-8)\n"
        << "endif()\n";
    return stream.str();
}

std::string BuildMainCppText()
{
    std::ostringstream stream;
    stream
        << "#include <imwidgetv4/app/ApplicationHost.h>\n\n"
        << "#if !defined(__ANDROID__)\n"
        << "int main(int argc, char** argv)\n"
        << "{\n"
        << "    (void)argc;\n"
        << "    (void)argv;\n"
        << "    return ImWidgetV4::RunHostedDesktopApplication();\n"
        << "}\n"
        << "#endif\n";
    return stream.str();
}

std::string BuildAppProjectConfigHeaderText()
{
    std::ostringstream stream;
    stream
        << "#pragma once\n\n"
        << "#include <imwidgetv4/app/ApplicationHost.h>\n\n";
    return stream.str();
}

std::string BuildAppProjectConfigSourceText(const FProjectScaffoldRequest& request)
{
    const FEditorApplicationSettings& settings = request.ApplicationSettings;
    const std::string title = settings.Title.empty() ? request.ProjectName : settings.Title;
    std::ostringstream stream;
    stream
        << "#include \"AppProjectConfig.h\"\n\n"
        << "#include <imwidgetv4/core/Application.h>\n"
        << "#include <imwidgetv4/core/Types.h>\n"
        << "#include <imwidgetv4/widgets/Button.h>\n"
        << "#include <imwidgetv4/widgets/TextBlock.h>\n"
        << "#include <imwidgetv4/widgets/TitleBar.h>\n"
        << "#include <imwidgetv4/widgets/VerticalBox.h>\n"
        << "#include <filesystem>\n"
        << "#include <memory>\n"
        << "#include <string>\n\n"
        << "#include \"" << request.StartupWidgetClassName << ".h\"\n";
    if (settings.bUseTitleBar && request.TitleBarRootWidget) {
        stream
            << "#include \"" << request.TitleBarWidgetClassName << ".h\"\n";
    }
    stream
        << "\n"
        << "namespace {\n\n"
        << "class FGeneratedAppHostDelegate final : public ImWidgetV4::IApplicationHostDelegate\n"
        << "{\n"
        << "public:\n"
        << "    ImWidgetV4::FApplicationHostConfig GetHostConfig() const override\n"
        << "    {\n"
        << "        ImWidgetV4::FApplicationHostConfig config;\n"
        << "        config.Title = " << BuildStringLiteral(title) << ";\n"
        << "        config.InitialWidth = " << std::max(1, settings.InitialWidth) << ";\n"
        << "        config.InitialHeight = " << std::max(1, settings.InitialHeight) << ";\n"
        << "        config.bUseCustomHostChrome = " << (settings.bUseCustomHostChrome ? "true" : "false") << ";\n";
    if (!settings.IconPath.empty()) {
        stream
            << "        // TODO: load application icon from " << settings.IconPath.generic_string() << " when a runtime image loader is available.\n";
    }
    if (settings.bEnableIniSettings && !settings.IniSettingsPath.empty()) {
        stream
            << "        config.IniSettingsPath = std::filesystem::path(" << BuildPathLiteral(settings.IniSettingsPath) << ");\n";
    }
    stream
        << "        return config;\n"
        << "    }\n\n"
        << "    void ConfigureApplication(ImWidgetV4::ImApplication& application) override\n"
        << "    {\n";
    if (!settings.DefaultTheme.empty()) {
        stream
            << "        application.SetActiveTheme(" << BuildStringLiteral(settings.DefaultTheme) << ");\n";
    }
    if (!settings.DefaultCulture.empty()) {
        stream
            << "        application.SetCulture(" << BuildStringLiteral(settings.DefaultCulture) << ");\n";
    }
    for (const std::filesystem::path& stringTablePath : settings.StringTablePaths) {
        if (!stringTablePath.empty()) {
            stream
                << "        application.LoadStringTable(std::filesystem::path(" << BuildPathLiteral(stringTablePath) << "));\n";
        }
    }
    stream
        << "        application.SetApplicationTitle(" << BuildStringLiteral(title) << ");\n";

    if (settings.bUseTitleBar && request.TitleBarRootWidget) {
        stream
            << "        auto rootLayout = std::make_shared<ImWidgetV4::ImVerticalBox>();\n"
            << "        rootLayout->SetSpacing(0.0f);\n"
            << "        auto titleBarView = std::make_shared<" << request.NamespaceName << "::" << request.TitleBarWidgetClassName << ">();\n"
            << "        rootLayout->AddChild(titleBarView, ImWidgetV4::FMargin(0.0f));\n"
            << "        rootLayout->AddChildFill(std::make_shared<" << request.NamespaceName << "::" << request.StartupWidgetClassName << ">(), 1.0f, ImWidgetV4::FMargin(0.0f));\n"
            << "        application.SetRootWidget(rootLayout);\n";
    } else {
        stream
            << "        application.SetRootWidget(std::make_shared<" << request.NamespaceName << "::" << request.StartupWidgetClassName << ">());\n";
    }

    stream
        << "    }\n";

    if (settings.bGenerateInitializeStub) {
        stream
            << "\n"
            << "    bool InitializeApplication(ImWidgetV4::ImApplication& application, ImWidgetV4::ImApplicationBackend& backend) override\n"
            << "    {\n"
            << "        (void)application;\n"
            << "        (void)backend;\n"
            << "        return true;\n"
            << "    }\n";
    }
    if (settings.bGenerateTickStub) {
        stream
            << "\n"
            << "    void Tick(ImWidgetV4::ImApplication& application, const ImWidgetV4::FFrameInfo& frameInfo) override\n"
            << "    {\n"
            << "        (void)application;\n"
            << "        (void)frameInfo;\n"
            << "    }\n";
    }

    stream
        << "};\n\n"
        << "} // namespace\n\n"
        << "namespace ImWidgetV4 {\n\n"
        << "std::shared_ptr<IApplicationHostDelegate> CreateApplicationHostDelegate()\n"
        << "{\n"
        << "    return std::make_shared<FGeneratedAppHostDelegate>();\n"
        << "}\n\n"
        << "} // namespace ImWidgetV4\n";
    return stream.str();
}

FProjectScaffoldResult GenerateBlankAppCode(const FProjectScaffoldRequest& request)
{
    FProjectScaffoldResult result;
    if (request.ProjectRoot.empty()) {
        result.ErrorMessage = "Project root is empty.";
        return result;
    }
    if (!request.StartupRootWidget) {
        result.ErrorMessage = "Startup widget tree is empty.";
        return result;
    }

    FCodeGenOptions codeGenOptions;
    codeGenOptions.ClassName = request.StartupWidgetClassName;
    codeGenOptions.Namespace = request.NamespaceName;
    const FCodeGenResult generatedCode =
        WidgetTreeToCppGenerator::Generate(request.StartupRootWidget, codeGenOptions);
    if (!generatedCode.bSuccess) {
        result.ErrorMessage = generatedCode.ErrorMessage.empty()
            ? std::string("Startup widget code generation failed.")
            : generatedCode.ErrorMessage;
        return result;
    }

    FCodeGenResult generatedTitleBarCode;
    if (request.TitleBarRootWidget) {
        FCodeGenOptions titleBarCodeGenOptions;
        titleBarCodeGenOptions.ClassName = request.TitleBarWidgetClassName;
        titleBarCodeGenOptions.Namespace = request.NamespaceName;
        generatedTitleBarCode = WidgetTreeToCppGenerator::Generate(
            request.TitleBarRootWidget,
            titleBarCodeGenOptions);
        if (!generatedTitleBarCode.bSuccess) {
            result.ErrorMessage = generatedTitleBarCode.ErrorMessage.empty()
                ? std::string("Title bar widget code generation failed.")
                : generatedTitleBarCode.ErrorMessage;
            return result;
        }
    }

    std::string errorMessage;

    const std::filesystem::path appProjectConfigHeaderPath =
        request.ProjectRoot / "generated" / "AppProjectConfig.h";
    if (!WriteTextFile(appProjectConfigHeaderPath, BuildAppProjectConfigHeaderText(), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(appProjectConfigHeaderPath);

    const std::filesystem::path appProjectConfigSourcePath =
        request.ProjectRoot / "generated" / "AppProjectConfig.cpp";
    if (!WriteTextFile(appProjectConfigSourcePath, BuildAppProjectConfigSourceText(request), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(appProjectConfigSourcePath);

    const std::filesystem::path generatedHeaderPath =
        request.ProjectRoot / "generated" / generatedCode.Files.HeaderFileName;
    if (!WriteTextFile(generatedHeaderPath, generatedCode.Files.HeaderText, errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(generatedHeaderPath);

    const std::filesystem::path generatedSourcePath =
        request.ProjectRoot / "generated" / generatedCode.Files.SourceFileName;
    if (!WriteTextFile(generatedSourcePath, generatedCode.Files.SourceText, errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(generatedSourcePath);

    if (request.TitleBarRootWidget) {
        const std::filesystem::path titleBarHeaderPath =
            request.ProjectRoot / "generated" / generatedTitleBarCode.Files.HeaderFileName;
        if (!WriteTextFile(titleBarHeaderPath, generatedTitleBarCode.Files.HeaderText, errorMessage)) {
            result.ErrorMessage = errorMessage;
            return result;
        }
        result.GeneratedFiles.push_back(titleBarHeaderPath);

        const std::filesystem::path titleBarSourcePath =
            request.ProjectRoot / "generated" / generatedTitleBarCode.Files.SourceFileName;
        if (!WriteTextFile(titleBarSourcePath, generatedTitleBarCode.Files.SourceText, errorMessage)) {
            result.ErrorMessage = errorMessage;
            return result;
        }
        result.GeneratedFiles.push_back(titleBarSourcePath);
    }

    result.bSuccess = true;
    return result;
}

FProjectScaffoldResult ScaffoldBlankApp(const FProjectScaffoldRequest& request)
{
    FProjectScaffoldResult result;
    if (request.ProjectRoot.empty()) {
        result.ErrorMessage = "Project root is empty.";
        return result;
    }

    const std::string cmakeProjectName = NormalizeIdentifier(request.ProjectName, "ImWidgetApp");
    std::string errorMessage;

    const std::filesystem::path rootCMakeListsPath = request.ProjectRoot / "CMakeLists.txt";
    if (!WriteTextFile(rootCMakeListsPath, BuildRootCMakeListsText(request, cmakeProjectName), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(rootCMakeListsPath);

    const std::filesystem::path userProjectCMakePath = request.ProjectRoot / "cmake" / "UserProject.cmake";
    if (!WriteTextFile(userProjectCMakePath, BuildUserProjectCMakeText(), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(userProjectCMakePath);

    const std::filesystem::path mainCppPath = request.ProjectRoot / "src" / "main.cpp";
    if (!WriteTextFile(mainCppPath, BuildMainCppText(), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }
    result.GeneratedFiles.push_back(mainCppPath);

    FProjectScaffoldResult codeResult = ProjectScaffolder::GenerateCode(request);
    if (!codeResult.bSuccess) {
        return codeResult;
    }
    result.GeneratedFiles.insert(
        result.GeneratedFiles.end(),
        codeResult.GeneratedFiles.begin(),
        codeResult.GeneratedFiles.end());
    result.bSuccess = true;
    return result;
}

} // namespace

FProjectScaffoldResult ProjectScaffolder::GenerateCMake(const FProjectScaffoldRequest& request)
{
    FProjectScaffoldResult result;
    if (request.ProjectRoot.empty()) {
        result.ErrorMessage = "Project root is empty.";
        return result;
    }

    std::string errorMessage;
    const std::filesystem::path generatedCMakePath =
        request.ProjectRoot / "cmake" / "ImWidgetV4GeneratedProject.cmake";
    if (!WriteTextFile(generatedCMakePath, BuildGeneratedProjectCMakeText(request), errorMessage)) {
        result.ErrorMessage = errorMessage;
        return result;
    }

    result.GeneratedFiles.push_back(generatedCMakePath);
    result.bSuccess = true;
    return result;
}

FProjectScaffoldResult ProjectScaffolder::GenerateCode(const FProjectScaffoldRequest& request)
{
    if (request.TemplateName.empty() || request.TemplateName == "Blank App") {
        FProjectScaffoldResult codeResult = GenerateBlankAppCode(request);
        if (!codeResult.bSuccess) {
            return codeResult;
        }

        FProjectScaffoldResult cmakeResult = GenerateCMake(request);
        if (!cmakeResult.bSuccess) {
            return cmakeResult;
        }

        codeResult.GeneratedFiles.insert(
            codeResult.GeneratedFiles.end(),
            cmakeResult.GeneratedFiles.begin(),
            cmakeResult.GeneratedFiles.end());
        return codeResult;
    }

    FProjectScaffoldResult result;
    result.ErrorMessage = "Unsupported project template: " + request.TemplateName;
    return result;
}

FProjectScaffoldResult ProjectScaffolder::Scaffold(const FProjectScaffoldRequest& request)
{
    if (request.TemplateName.empty() || request.TemplateName == "Blank App") {
        return ScaffoldBlankApp(request);
    }

    FProjectScaffoldResult result;
    result.ErrorMessage = "Unsupported project template: " + request.TemplateName;
    return result;
}

} // namespace ImWidgetV4Editor
