# 演示程序通用配置

# 添加各个演示子目录
add_subdirectory(ButtonDemo)
add_subdirectory(BoxPanelDemo)
add_subdirectory(CanvasPanelDemo)
add_subdirectory(ExpandableBoxDemo)
add_subdirectory(ImageDemo)
add_subdirectory(InputWidgetsDemo)
add_subdirectory(ReflectionInspectorDemo)
add_subdirectory(ScrollBoxDemo)
add_subdirectory(SplitterDemo)
add_subdirectory(TextListDemo)
add_subdirectory(UserWidgetDemo)
add_subdirectory(WindowDemo)
# add_subdirectory(TextBlockDemo)
# 后续添加更多演示...
