#include "../src/editor/DocumentSnapshotExporter.h"
#include "../src/editor/EditorDocument.h"
#include "../src/editor/EditorPaths.h"
#include "../src/cli/UiDocumentCli.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <imwidgetv4/widgets/TextBlock.h>
#include <imwidgetv4/widgets/VerticalBox.h>
#include <cstdlib>
#include <optional>
#include <string>

#if defined(_WIN32)
#include <windows.h>
#endif

using namespace ImWidgetV4;
using namespace ImWidgetV4Editor;

namespace {

std::shared_ptr<ImWidget> BuildSnapshotRoot()
{
    auto root = std::make_shared<ImVerticalBox>();
    root->SetName("SnapshotRoot");
    root->SetSpacing(6.0f);

    auto title = std::make_shared<ImTextBlock>();
    title->SetName("TitleText");
    title->SetText("Snapshot Export");
    title->SetFontSize(24.0f);
    root->AddChild(title);

    auto body = std::make_shared<ImTextBlock>();
    body->SetName("BodyText");
    body->SetText("Generated by the editor CLI.");
    root->AddChild(body);

    return root;
}

std::filesystem::path CreateSnapshotFixtureDocument(const std::filesystem::path& directory)
{
    const std::filesystem::path inputPath = directory / "fixture.ui.json";
    EditorDocument document;
    document.NewDocument(BuildSnapshotRoot(), "SnapshotFixture");
    std::string error;
    EXPECT_TRUE(document.SaveAs(inputPath, &error)) << error;
    return inputPath;
}

std::filesystem::path FindCliExecutable()
{
    const std::filesystem::path executableDirectory = GetEditorExecutableDirectory();
    const std::filesystem::path configName = executableDirectory.filename();
    const std::filesystem::path debugToolsDirectory =
        executableDirectory.parent_path().parent_path() / "bin" / "tools" / configName;
    const std::filesystem::path siblingToolsDirectory = executableDirectory.parent_path() / "tools" / configName;
    const std::filesystem::path localToolsDirectory = executableDirectory / "tools" / configName;

    const std::filesystem::path candidates[] = {
        executableDirectory / "ImWidgetEditorCLI.exe",
        executableDirectory.parent_path() / "ImWidgetEditorCLI.exe",
        debugToolsDirectory / "ImWidgetEditorCLI.exe",
        siblingToolsDirectory / "ImWidgetEditorCLI.exe",
        localToolsDirectory / "ImWidgetEditorCLI.exe",
    };

    for (const std::filesystem::path& candidate : candidates) {
        if (std::filesystem::exists(candidate)) {
            return candidate;
        }
    }

    return {};
}

std::string QuoteCommandArgument(const std::filesystem::path& path)
{
    return "\"" + path.string() + "\"";
}

int RunCliCommand(const std::filesystem::path& executable, const std::filesystem::path& inputPath, const std::filesystem::path& outputPath)
{
#if defined(_WIN32)
    const std::wstring commandLine =
        L"\"" + executable.wstring() + L"\" snapshot export \"" +
        inputPath.wstring() + L"\" \"" + outputPath.wstring() + L"\"";

    STARTUPINFOW startupInfo{};
    startupInfo.cb = sizeof(startupInfo);
    PROCESS_INFORMATION processInformation{};
    std::wstring mutableCommandLine = commandLine;
    if (!CreateProcessW(
            nullptr,
            mutableCommandLine.data(),
            nullptr,
            nullptr,
            FALSE,
            0,
            nullptr,
            nullptr,
            &startupInfo,
            &processInformation)) {
        return -1;
    }

    WaitForSingleObject(processInformation.hProcess, INFINITE);
    DWORD exitCode = 1;
    GetExitCodeProcess(processInformation.hProcess, &exitCode);
    CloseHandle(processInformation.hProcess);
    CloseHandle(processInformation.hThread);
    return static_cast<int>(exitCode);
#else
    const std::string command =
        QuoteCommandArgument(executable) + " snapshot export " +
        QuoteCommandArgument(inputPath) + " " + QuoteCommandArgument(outputPath);
    return std::system(command.c_str());
#endif
}

} // namespace

TEST(EditorSnapshotExportTest, ExportsMinimalUiDocumentWithAdaptiveSize)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    errorCode.clear();
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "exported" / "snapshot.png";

    const FDocumentSnapshotExportResult result = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {inputPath, outputPath, std::nullopt, std::nullopt});

    ASSERT_TRUE(result.bSuccess) << result.ErrorMessage;
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
    EXPECT_GT(result.ExportSize.X, 0.0f);
    EXPECT_GT(result.ExportSize.Y, 0.0f);
}

TEST(EditorSnapshotExportTest, AppliesExplicitWidthAndHeightOverride)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_override";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    errorCode.clear();
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "override.png";

    const FDocumentSnapshotExportResult result = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {inputPath, outputPath, 640, 360});

    ASSERT_TRUE(result.bSuccess) << result.ErrorMessage;
    EXPECT_FLOAT_EQ(result.ExportSize.X, 640.0f);
    EXPECT_FLOAT_EQ(result.ExportSize.Y, 360.0f);
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
}

TEST(EditorSnapshotExportTest, RejectsInvalidInputAndMissingPaths)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_invalid";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path invalidPath = tempDirectory / "invalid.ui.json";
    {
        std::ofstream stream(invalidPath);
        stream << "{";
    }

    const FDocumentSnapshotExportResult invalidResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {invalidPath, tempDirectory / "invalid.png", std::nullopt, std::nullopt});
    EXPECT_FALSE(invalidResult.bSuccess);
    EXPECT_NE(invalidResult.ErrorMessage.find("Failed to load UI document"), std::string::npos);

    const FDocumentSnapshotExportResult missingInputResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {{}, tempDirectory / "missing.png", std::nullopt, std::nullopt});
    EXPECT_FALSE(missingInputResult.bSuccess);
    EXPECT_NE(missingInputResult.ErrorMessage.find("Input UI document path is required"), std::string::npos);

    const FDocumentSnapshotExportResult missingOutputResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {invalidPath, {}, std::nullopt, std::nullopt});
    EXPECT_FALSE(missingOutputResult.bSuccess);
    EXPECT_NE(missingOutputResult.ErrorMessage.find("Output PNG path is required"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliValidatesAndBuildsTreeInfo)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    std::string error;
    EXPECT_TRUE(UiDocumentCli::ValidateDocumentFile(inputPath, &error)) << error;

    const FUiDocumentTreeInfo treeInfo = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(treeInfo.bSuccess) << treeInfo.ErrorMessage;
    ASSERT_EQ(treeInfo.Nodes.size(), 3u);

    EXPECT_EQ(treeInfo.Nodes[0].WidgetId, "w1");
    EXPECT_EQ(treeInfo.Nodes[0].TypeName, "ImVerticalBox");
    EXPECT_EQ(treeInfo.Nodes[0].Name, "SnapshotRoot");
    EXPECT_EQ(treeInfo.Nodes[0].Depth, 0u);

    EXPECT_EQ(treeInfo.Nodes[1].WidgetId, "w2");
    EXPECT_EQ(treeInfo.Nodes[1].TypeName, "ImTextBlock");
    EXPECT_EQ(treeInfo.Nodes[1].Name, "TitleText");
    EXPECT_EQ(treeInfo.Nodes[1].Depth, 1u);

    const std::filesystem::path invalidPath = tempDirectory / "invalid.ui.json";
    {
        std::ofstream stream(invalidPath);
        stream << "{";
    }

    EXPECT_FALSE(UiDocumentCli::ValidateDocumentFile(invalidPath, &error));
    const FUiDocumentTreeInfo invalidTreeInfo = UiDocumentCli::BuildDocumentTreeInfo(invalidPath);
    EXPECT_FALSE(invalidTreeInfo.bSuccess);
    EXPECT_FALSE(invalidTreeInfo.ErrorMessage.empty());
}

TEST(EditorSnapshotExportTest, UiDocumentCliFindsNodesByFilters)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_find";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    FUiFindRequest typeRequest;
    typeRequest.TypeName = "ImTextBlock";
    const FUiDocumentTreeInfo textBlocks = UiDocumentCli::FindNodes(inputPath, typeRequest);
    ASSERT_TRUE(textBlocks.bSuccess) << textBlocks.ErrorMessage;
    ASSERT_EQ(textBlocks.Nodes.size(), 2u);
    EXPECT_EQ(textBlocks.Nodes[0].WidgetId, "w2");
    EXPECT_EQ(textBlocks.Nodes[1].WidgetId, "w3");

    FUiFindRequest nameRequest;
    nameRequest.Name = "TitleText";
    const FUiDocumentTreeInfo titleNodes = UiDocumentCli::FindNodes(inputPath, nameRequest);
    ASSERT_TRUE(titleNodes.bSuccess) << titleNodes.ErrorMessage;
    ASSERT_EQ(titleNodes.Nodes.size(), 1u);
    EXPECT_EQ(titleNodes.Nodes[0].WidgetId, "w2");

    FUiFindRequest combinedRequest;
    combinedRequest.TypeName = "ImTextBlock";
    combinedRequest.Name = "Missing";
    const FUiDocumentTreeInfo missingNodes = UiDocumentCli::FindNodes(inputPath, combinedRequest);
    ASSERT_TRUE(missingNodes.bSuccess) << missingNodes.ErrorMessage;
    EXPECT_TRUE(missingNodes.Nodes.empty());
}

TEST(EditorSnapshotExportTest, UiDocumentCliFormatsDocument)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_format";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult formatResult = UiDocumentCli::FormatDocumentFile(inputPath);
    ASSERT_TRUE(formatResult.bSuccess) << formatResult.ErrorMessage;
    EXPECT_EQ(formatResult.Node.WidgetId, "w1");
    EXPECT_EQ(formatResult.Node.TypeName, "ImVerticalBox");

    std::string error;
    EXPECT_TRUE(UiDocumentCli::ValidateDocumentFile(inputPath, &error)) << error;

    const FUiDocumentTreeInfo treeInfo = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(treeInfo.bSuccess) << treeInfo.ErrorMessage;
    EXPECT_EQ(treeInfo.Nodes.size(), 3u);
}

TEST(EditorSnapshotExportTest, UiDocumentCliInspectsNodeById)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_inspect";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiNodeInspectInfo rootInfo = UiDocumentCli::InspectNode(inputPath, "w1");
    ASSERT_TRUE(rootInfo.bSuccess) << rootInfo.ErrorMessage;
    EXPECT_EQ(rootInfo.Node.WidgetId, "w1");
    EXPECT_EQ(rootInfo.Node.TypeName, "ImVerticalBox");
    EXPECT_EQ(rootInfo.Node.Name, "SnapshotRoot");
    ASSERT_EQ(rootInfo.Children.size(), 2u);
    EXPECT_EQ(rootInfo.Children[0].WidgetId, "w2");
    EXPECT_EQ(rootInfo.Children[0].TypeName, "ImTextBlock");

    const FUiNodeInspectInfo titleInfo = UiDocumentCli::InspectNode(inputPath, "w2");
    ASSERT_TRUE(titleInfo.bSuccess) << titleInfo.ErrorMessage;
    EXPECT_EQ(titleInfo.Node.Name, "TitleText");
    ASSERT_TRUE(titleInfo.Properties.is_object());
    ASSERT_TRUE(titleInfo.Properties.contains("ImTextBlock::Text"));
    EXPECT_EQ(titleInfo.Properties["ImTextBlock::Text"], "Snapshot Export");

    const FUiNodeInspectInfo missingInfo = UiDocumentCli::InspectNode(inputPath, "missing");
    EXPECT_FALSE(missingInfo.bSuccess);
    EXPECT_NE(missingInfo.ErrorMessage.find("missing"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliGetEquivalentDataFromInspect)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_get";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    errorCode.clear();
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiNodeInspectInfo inspectInfo = UiDocumentCli::InspectNode(inputPath, "w2");
    ASSERT_TRUE(inspectInfo.bSuccess) << inspectInfo.ErrorMessage;
    ASSERT_TRUE(inspectInfo.Properties.contains("ImTextBlock::Text"));
    EXPECT_EQ(inspectInfo.Properties["ImTextBlock::Text"], "Snapshot Export");
}

TEST(EditorSnapshotExportTest, UiDocumentCliRenamesNodeAndSavesDocument)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_rename";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult renameResult = UiDocumentCli::RenameNode(inputPath, "w2", "RenamedTitle");
    ASSERT_TRUE(renameResult.bSuccess) << renameResult.ErrorMessage;
    EXPECT_TRUE(renameResult.bChanged);
    EXPECT_EQ(renameResult.Node.WidgetId, "w2");
    EXPECT_EQ(renameResult.Node.Name, "RenamedTitle");

    const FUiNodeInspectInfo inspectInfo = UiDocumentCli::InspectNode(inputPath, "w2");
    ASSERT_TRUE(inspectInfo.bSuccess) << inspectInfo.ErrorMessage;
    EXPECT_EQ(inspectInfo.Node.Name, "RenamedTitle");

    const FUiMutationResult unchangedResult = UiDocumentCli::RenameNode(inputPath, "w2", "RenamedTitle");
    ASSERT_TRUE(unchangedResult.bSuccess) << unchangedResult.ErrorMessage;
    EXPECT_FALSE(unchangedResult.bChanged);

    const FUiMutationResult missingResult = UiDocumentCli::RenameNode(inputPath, "missing", "Nope");
    EXPECT_FALSE(missingResult.bSuccess);
    EXPECT_NE(missingResult.ErrorMessage.find("missing"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliSetsReflectedPropertyAndSavesDocument)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_set";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult textResult =
        UiDocumentCli::SetNodeProperty(inputPath, "w2", "Text", json("Updated Title"));
    ASSERT_TRUE(textResult.bSuccess) << textResult.ErrorMessage;
    EXPECT_TRUE(textResult.bChanged);

    const FUiMutationResult visibleResult =
        UiDocumentCli::SetNodeProperty(inputPath, "w2", "Visible", json(false));
    ASSERT_TRUE(visibleResult.bSuccess) << visibleResult.ErrorMessage;
    EXPECT_TRUE(visibleResult.bChanged);

    const FUiMutationResult alignmentResult =
        UiDocumentCli::SetNodeProperty(inputPath, "w2", "TextAlignment", json("Right"));
    ASSERT_TRUE(alignmentResult.bSuccess) << alignmentResult.ErrorMessage;
    EXPECT_TRUE(alignmentResult.bChanged);

    const FUiNodeInspectInfo inspectInfo = UiDocumentCli::InspectNode(inputPath, "w2");
    ASSERT_TRUE(inspectInfo.bSuccess) << inspectInfo.ErrorMessage;
    EXPECT_EQ(inspectInfo.Properties["ImTextBlock::Text"], "Updated Title");
    EXPECT_EQ(inspectInfo.Properties["ImWidget::Visible"], false);
    EXPECT_EQ(inspectInfo.Properties["ImTextBlock::TextAlignment"], "Right");

    const FUiMutationResult missingPropertyResult =
        UiDocumentCli::SetNodeProperty(inputPath, "w2", "NotAProperty", json(1));
    EXPECT_FALSE(missingPropertyResult.bSuccess);
    EXPECT_NE(missingPropertyResult.ErrorMessage.find("NotAProperty"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliAddsAndRemovesNode)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_add_remove";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult addResult = UiDocumentCli::AddNode(inputPath, "w1", "ImTextBlock");
    ASSERT_TRUE(addResult.bSuccess) << addResult.ErrorMessage;
    EXPECT_TRUE(addResult.bChanged);
    EXPECT_EQ(addResult.Node.TypeName, "ImTextBlock");
    EXPECT_EQ(addResult.Node.Name, "TextBlock");

    const FUiDocumentTreeInfo afterAddTree = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(afterAddTree.bSuccess) << afterAddTree.ErrorMessage;
    ASSERT_EQ(afterAddTree.Nodes.size(), 4u);
    const std::string addedId = afterAddTree.Nodes.back().WidgetId;
    EXPECT_EQ(afterAddTree.Nodes.back().TypeName, "ImTextBlock");

    const FUiMutationResult removeResult = UiDocumentCli::RemoveNode(inputPath, addedId);
    ASSERT_TRUE(removeResult.bSuccess) << removeResult.ErrorMessage;
    EXPECT_TRUE(removeResult.bChanged);
    EXPECT_EQ(removeResult.Node.WidgetId, addedId);

    const FUiDocumentTreeInfo afterRemoveTree = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(afterRemoveTree.bSuccess) << afterRemoveTree.ErrorMessage;
    EXPECT_EQ(afterRemoveTree.Nodes.size(), 3u);

    const FUiMutationResult removeRootResult = UiDocumentCli::RemoveNode(inputPath, "w1");
    EXPECT_FALSE(removeRootResult.bSuccess);
    EXPECT_NE(removeRootResult.ErrorMessage.find("root"), std::string::npos);

    const FUiMutationResult unsupportedAddResult = UiDocumentCli::AddNode(inputPath, "w1", "ImNotAWidget");
    EXPECT_FALSE(unsupportedAddResult.bSuccess);
    EXPECT_NE(unsupportedAddResult.ErrorMessage.find("Unsupported"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliDuplicatesNode)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_duplicate";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult duplicateResult = UiDocumentCli::DuplicateNode(inputPath, "w2");
    ASSERT_TRUE(duplicateResult.bSuccess) << duplicateResult.ErrorMessage;
    EXPECT_TRUE(duplicateResult.bChanged);
    EXPECT_EQ(duplicateResult.Node.TypeName, "ImTextBlock");
    EXPECT_EQ(duplicateResult.Node.Name, "TitleTextCopy");

    const FUiDocumentTreeInfo treeInfo = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(treeInfo.bSuccess) << treeInfo.ErrorMessage;
    ASSERT_EQ(treeInfo.Nodes.size(), 4u);

    const FUiNodeInspectInfo cloneInfo = UiDocumentCli::InspectNode(inputPath, treeInfo.Nodes.back().WidgetId);
    ASSERT_TRUE(cloneInfo.bSuccess) << cloneInfo.ErrorMessage;
    EXPECT_EQ(cloneInfo.Properties["ImTextBlock::Text"], "Snapshot Export");

    const FUiMutationResult duplicateRootResult = UiDocumentCli::DuplicateNode(inputPath, "w1");
    EXPECT_FALSE(duplicateRootResult.bSuccess);
    EXPECT_NE(duplicateRootResult.ErrorMessage.find("root"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliMovesNode)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_move";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    const FUiMutationResult addContainerResult = UiDocumentCli::AddNode(inputPath, "w1", "ImVerticalBox");
    ASSERT_TRUE(addContainerResult.bSuccess) << addContainerResult.ErrorMessage;
    const std::string containerId = addContainerResult.Node.WidgetId;

    const FUiMutationResult moveResult = UiDocumentCli::MoveNode(inputPath, "w2", containerId);
    ASSERT_TRUE(moveResult.bSuccess) << moveResult.ErrorMessage;
    EXPECT_TRUE(moveResult.bChanged);
    EXPECT_EQ(moveResult.Node.WidgetId, "w2");
    EXPECT_EQ(moveResult.Node.TypeName, "ImTextBlock");
    EXPECT_EQ(moveResult.Node.Depth, 2u);

    const FUiDocumentTreeInfo treeInfo = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(treeInfo.bSuccess) << treeInfo.ErrorMessage;
    ASSERT_EQ(treeInfo.Nodes.size(), 4u);
    EXPECT_EQ(treeInfo.Nodes.back().WidgetId, "w2");
    EXPECT_EQ(treeInfo.Nodes.back().Depth, 2u);

    const FUiMutationResult sameParentResult = UiDocumentCli::MoveNode(inputPath, "w2", containerId);
    ASSERT_TRUE(sameParentResult.bSuccess) << sameParentResult.ErrorMessage;
    EXPECT_FALSE(sameParentResult.bChanged);

    const FUiMutationResult moveRootResult = UiDocumentCli::MoveNode(inputPath, "w1", "w2");
    EXPECT_FALSE(moveRootResult.bSuccess);
    EXPECT_NE(moveRootResult.ErrorMessage.find("root"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliDiffsDocuments)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_diff";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    errorCode.clear();
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path beforePath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path afterPath = tempDirectory / "after.ui.json";
    std::filesystem::copy_file(beforePath, afterPath, std::filesystem::copy_options::overwrite_existing, errorCode);
    ASSERT_FALSE(errorCode);

    const FUiMutationResult renameResult = UiDocumentCli::RenameNode(afterPath, "w2", "ChangedTitle");
    ASSERT_TRUE(renameResult.bSuccess) << renameResult.ErrorMessage;
    const FUiMutationResult setResult =
        UiDocumentCli::SetNodeProperty(afterPath, "w2", "Text", json("Changed Text"));
    ASSERT_TRUE(setResult.bSuccess) << setResult.ErrorMessage;
    const FUiMutationResult addResult = UiDocumentCli::AddNode(afterPath, "w1", "ImTextBlock");
    ASSERT_TRUE(addResult.bSuccess) << addResult.ErrorMessage;

    const FUiDocumentDiffInfo diffInfo = UiDocumentCli::DiffDocuments(beforePath, afterPath);
    ASSERT_TRUE(diffInfo.bSuccess) << diffInfo.ErrorMessage;
    EXPECT_TRUE(diffInfo.bChanged);

    bool bFoundNameChange = false;
    bool bFoundTextChange = false;
    bool bFoundAdd = false;
    for (const FUiNodeDiffEntry& entry : diffInfo.Entries) {
        if (entry.Kind == "changed" && entry.WidgetId == "w2" && entry.FieldName == "name") {
            bFoundNameChange = true;
            EXPECT_EQ(entry.BeforeValue, "TitleText");
            EXPECT_EQ(entry.AfterValue, "ChangedTitle");
        }
        if (entry.Kind == "property" && entry.WidgetId == "w2" && entry.FieldName == "ImTextBlock::Text") {
            bFoundTextChange = true;
            EXPECT_EQ(entry.BeforeValue, "Snapshot Export");
            EXPECT_EQ(entry.AfterValue, "Changed Text");
        }
        if (entry.Kind == "added" && entry.AfterNode.TypeName == "ImTextBlock") {
            bFoundAdd = true;
        }
    }

    EXPECT_TRUE(bFoundNameChange);
    EXPECT_TRUE(bFoundTextChange);
    EXPECT_TRUE(bFoundAdd);

    const FUiDocumentDiffInfo unchangedInfo = UiDocumentCli::DiffDocuments(beforePath, beforePath);
    ASSERT_TRUE(unchangedInfo.bSuccess) << unchangedInfo.ErrorMessage;
    EXPECT_FALSE(unchangedInfo.bChanged);
    EXPECT_TRUE(unchangedInfo.Entries.empty());
}

TEST(EditorSnapshotExportTest, UiDocumentCliLintsDocuments)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli_lint";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    errorCode.clear();
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path cleanPath = CreateSnapshotFixtureDocument(tempDirectory);
    const FUiLintInfo cleanInfo = UiDocumentCli::LintDocumentFile(cleanPath);
    ASSERT_TRUE(cleanInfo.bSuccess) << cleanInfo.ErrorMessage;
    EXPECT_TRUE(cleanInfo.Diagnostics.empty());

    const std::filesystem::path lintPath = tempDirectory / "lint.ui.json";
    std::filesystem::copy_file(cleanPath, lintPath, std::filesystem::copy_options::overwrite_existing, errorCode);
    ASSERT_FALSE(errorCode);

    EditorDocument document;
    std::string error;
    ASSERT_TRUE(document.Load(lintPath, &error)) << error;
    json documentJson = document.ExportDocumentJson();
    json& children = documentJson["RootWidget"]["Children"];
    ASSERT_TRUE(children.is_array());
    ASSERT_GE(children.size(), 2u);
    children[0]["Properties"]["ImWidget::Name"] = "";
    children[0]["Properties"]["ImTextBlock::NotAProperty"] = 1;
    children[1]["EditorId"] = children[0]["EditorId"];
    {
        std::ofstream stream(lintPath, std::ios::binary | std::ios::trunc);
        stream << documentJson.dump(2);
    }

    const FUiLintInfo lintInfo = UiDocumentCli::LintDocumentFile(lintPath);
    ASSERT_TRUE(lintInfo.bSuccess) << lintInfo.ErrorMessage;

    bool bFoundEmptyName = false;
    bool bFoundUnknownProperty = false;
    bool bFoundDuplicateId = false;
    for (const FUiLintDiagnostic& diagnostic : lintInfo.Diagnostics) {
        if (diagnostic.Code == "empty_name") {
            bFoundEmptyName = true;
        }
        if (diagnostic.Code == "unknown_property" && diagnostic.FieldName == "ImTextBlock::NotAProperty") {
            bFoundUnknownProperty = true;
        }
        if (diagnostic.Code == "duplicate_editor_id") {
            bFoundDuplicateId = true;
            EXPECT_EQ(diagnostic.Severity, "error");
        }
    }

    EXPECT_TRUE(bFoundEmptyName);
    EXPECT_TRUE(bFoundUnknownProperty);
    EXPECT_TRUE(bFoundDuplicateId);
}

TEST(EditorSnapshotExportTest, CliExportsSnapshotPng)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_cli";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "cli" / "snapshot.png";

    const std::filesystem::path cliExecutable = FindCliExecutable();
    if (cliExecutable.empty()) {
        GTEST_SKIP() << "ImWidgetEditorCLI executable was not found in the local build tree.";
    }

    const int exitCode = RunCliCommand(cliExecutable, inputPath, outputPath);

    EXPECT_EQ(exitCode, 0);
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
}
