#include "../src/editor/DocumentSnapshotExporter.h"
#include "../src/editor/EditorDocument.h"
#include "../src/editor/EditorPaths.h"
#include "../src/cli/UiDocumentCli.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <imwidgetv4/widgets/TextBlock.h>
#include <imwidgetv4/widgets/VerticalBox.h>
#include <cstdlib>
#include <optional>
#include <string>

#if defined(_WIN32)
#include <windows.h>
#endif

using namespace ImWidgetV4;
using namespace ImWidgetV4Editor;

namespace {

std::shared_ptr<ImWidget> BuildSnapshotRoot()
{
    auto root = std::make_shared<ImVerticalBox>();
    root->SetName("SnapshotRoot");
    root->SetSpacing(6.0f);

    auto title = std::make_shared<ImTextBlock>();
    title->SetName("TitleText");
    title->SetText("Snapshot Export");
    title->SetFontSize(24.0f);
    root->AddChild(title);

    auto body = std::make_shared<ImTextBlock>();
    body->SetName("BodyText");
    body->SetText("Generated by the editor CLI.");
    root->AddChild(body);

    return root;
}

std::filesystem::path CreateSnapshotFixtureDocument(const std::filesystem::path& directory)
{
    const std::filesystem::path inputPath = directory / "fixture.ui.json";
    EditorDocument document;
    document.NewDocument(BuildSnapshotRoot(), "SnapshotFixture");
    std::string error;
    EXPECT_TRUE(document.SaveAs(inputPath, &error)) << error;
    return inputPath;
}

std::filesystem::path FindCliExecutable()
{
    const std::filesystem::path executableDirectory = GetEditorExecutableDirectory();
    const std::filesystem::path configName = executableDirectory.filename();
    const std::filesystem::path debugToolsDirectory =
        executableDirectory.parent_path().parent_path() / "bin" / "tools" / configName;
    const std::filesystem::path siblingToolsDirectory = executableDirectory.parent_path() / "tools" / configName;
    const std::filesystem::path localToolsDirectory = executableDirectory / "tools" / configName;

    const std::filesystem::path candidates[] = {
        executableDirectory / "ImWidgetEditorCLI.exe",
        executableDirectory.parent_path() / "ImWidgetEditorCLI.exe",
        debugToolsDirectory / "ImWidgetEditorCLI.exe",
        siblingToolsDirectory / "ImWidgetEditorCLI.exe",
        localToolsDirectory / "ImWidgetEditorCLI.exe",
    };

    for (const std::filesystem::path& candidate : candidates) {
        if (std::filesystem::exists(candidate)) {
            return candidate;
        }
    }

    return {};
}

std::string QuoteCommandArgument(const std::filesystem::path& path)
{
    return "\"" + path.string() + "\"";
}

int RunCliCommand(const std::filesystem::path& executable, const std::filesystem::path& inputPath, const std::filesystem::path& outputPath)
{
#if defined(_WIN32)
    const std::wstring commandLine =
        L"\"" + executable.wstring() + L"\" snapshot export \"" +
        inputPath.wstring() + L"\" \"" + outputPath.wstring() + L"\"";

    STARTUPINFOW startupInfo{};
    startupInfo.cb = sizeof(startupInfo);
    PROCESS_INFORMATION processInformation{};
    std::wstring mutableCommandLine = commandLine;
    if (!CreateProcessW(
            nullptr,
            mutableCommandLine.data(),
            nullptr,
            nullptr,
            FALSE,
            0,
            nullptr,
            nullptr,
            &startupInfo,
            &processInformation)) {
        return -1;
    }

    WaitForSingleObject(processInformation.hProcess, INFINITE);
    DWORD exitCode = 1;
    GetExitCodeProcess(processInformation.hProcess, &exitCode);
    CloseHandle(processInformation.hProcess);
    CloseHandle(processInformation.hThread);
    return static_cast<int>(exitCode);
#else
    const std::string command =
        QuoteCommandArgument(executable) + " snapshot export " +
        QuoteCommandArgument(inputPath) + " " + QuoteCommandArgument(outputPath);
    return std::system(command.c_str());
#endif
}

} // namespace

TEST(EditorSnapshotExportTest, ExportsMinimalUiDocumentWithAdaptiveSize)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "exported" / "snapshot.png";

    const FDocumentSnapshotExportResult result = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {inputPath, outputPath, std::nullopt, std::nullopt});

    ASSERT_TRUE(result.bSuccess) << result.ErrorMessage;
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
    EXPECT_GT(result.ExportSize.X, 0.0f);
    EXPECT_GT(result.ExportSize.Y, 0.0f);
}

TEST(EditorSnapshotExportTest, AppliesExplicitWidthAndHeightOverride)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_override";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "override.png";

    const FDocumentSnapshotExportResult result = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {inputPath, outputPath, 640, 360});

    ASSERT_TRUE(result.bSuccess) << result.ErrorMessage;
    EXPECT_FLOAT_EQ(result.ExportSize.X, 640.0f);
    EXPECT_FLOAT_EQ(result.ExportSize.Y, 360.0f);
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
}

TEST(EditorSnapshotExportTest, RejectsInvalidInputAndMissingPaths)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_invalid";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path invalidPath = tempDirectory / "invalid.ui.json";
    {
        std::ofstream stream(invalidPath);
        stream << "{";
    }

    const FDocumentSnapshotExportResult invalidResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {invalidPath, tempDirectory / "invalid.png", std::nullopt, std::nullopt});
    EXPECT_FALSE(invalidResult.bSuccess);
    EXPECT_NE(invalidResult.ErrorMessage.find("Failed to load UI document"), std::string::npos);

    const FDocumentSnapshotExportResult missingInputResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {{}, tempDirectory / "missing.png", std::nullopt, std::nullopt});
    EXPECT_FALSE(missingInputResult.bSuccess);
    EXPECT_NE(missingInputResult.ErrorMessage.find("Input UI document path is required"), std::string::npos);

    const FDocumentSnapshotExportResult missingOutputResult = DocumentSnapshotExporter::ExportToPng(
        FDocumentSnapshotExportRequest {invalidPath, {}, std::nullopt, std::nullopt});
    EXPECT_FALSE(missingOutputResult.bSuccess);
    EXPECT_NE(missingOutputResult.ErrorMessage.find("Output PNG path is required"), std::string::npos);
}

TEST(EditorSnapshotExportTest, UiDocumentCliValidatesAndBuildsTreeInfo)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_ui_document_cli";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);

    std::string error;
    EXPECT_TRUE(UiDocumentCli::ValidateDocumentFile(inputPath, &error)) << error;

    const FUiDocumentTreeInfo treeInfo = UiDocumentCli::BuildDocumentTreeInfo(inputPath);
    ASSERT_TRUE(treeInfo.bSuccess) << treeInfo.ErrorMessage;
    ASSERT_EQ(treeInfo.Nodes.size(), 3u);

    EXPECT_EQ(treeInfo.Nodes[0].WidgetId, "w1");
    EXPECT_EQ(treeInfo.Nodes[0].TypeName, "ImVerticalBox");
    EXPECT_EQ(treeInfo.Nodes[0].Name, "SnapshotRoot");
    EXPECT_EQ(treeInfo.Nodes[0].Depth, 0u);

    EXPECT_EQ(treeInfo.Nodes[1].WidgetId, "w2");
    EXPECT_EQ(treeInfo.Nodes[1].TypeName, "ImTextBlock");
    EXPECT_EQ(treeInfo.Nodes[1].Name, "TitleText");
    EXPECT_EQ(treeInfo.Nodes[1].Depth, 1u);

    const std::filesystem::path invalidPath = tempDirectory / "invalid.ui.json";
    {
        std::ofstream stream(invalidPath);
        stream << "{";
    }

    EXPECT_FALSE(UiDocumentCli::ValidateDocumentFile(invalidPath, &error));
    const FUiDocumentTreeInfo invalidTreeInfo = UiDocumentCli::BuildDocumentTreeInfo(invalidPath);
    EXPECT_FALSE(invalidTreeInfo.bSuccess);
    EXPECT_FALSE(invalidTreeInfo.ErrorMessage.empty());
}

TEST(EditorSnapshotExportTest, CliExportsSnapshotPng)
{
    const std::filesystem::path tempDirectory =
        std::filesystem::temp_directory_path() / "imwidgetv4_editor_snapshot_export_cli";
    std::error_code errorCode;
    std::filesystem::remove_all(tempDirectory, errorCode);
    std::filesystem::create_directories(tempDirectory, errorCode);
    ASSERT_FALSE(errorCode);

    const std::filesystem::path inputPath = CreateSnapshotFixtureDocument(tempDirectory);
    const std::filesystem::path outputPath = tempDirectory / "cli" / "snapshot.png";

    const std::filesystem::path cliExecutable = FindCliExecutable();
    if (cliExecutable.empty()) {
        GTEST_SKIP() << "ImWidgetEditorCLI executable was not found in the local build tree.";
    }

    const int exitCode = RunCliCommand(cliExecutable, inputPath, outputPath);

    EXPECT_EQ(exitCode, 0);
    EXPECT_TRUE(std::filesystem::exists(outputPath));
    EXPECT_GT(std::filesystem::file_size(outputPath), 0u);
}
