# Auto-generated by ImWidgetV4Editor. Do not edit manually.
# Use cmake/UserProject.cmake for user CMake customizations.

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(IMWIDGETV4_LIBRARY_MODE "Source" CACHE STRING "ImWidgetV4 integration mode: SDK or Source")
set_property(CACHE IMWIDGETV4_LIBRARY_MODE PROPERTY STRINGS SDK Source)
set(IMWIDGETV4_SDK_DIR "" CACHE PATH "Path to the ImWidgetV4 SDK CMake package directory")
set(IMWIDGETV4_ROOT "" CACHE PATH "Path to the ImWidgetV4 library root")
if(NOT IMWIDGETV4_LIBRARY_MODE STREQUAL "SDK" AND NOT IMWIDGETV4_LIBRARY_MODE STREQUAL "Source")
    message(FATAL_ERROR "IMWIDGETV4_LIBRARY_MODE must be SDK or Source.")
endif()

if(IMWIDGETV4_LIBRARY_MODE STREQUAL "SDK")
    if(IMWIDGETV4_SDK_DIR STREQUAL "")
        find_package(ImWidgetV4 0.1.0 CONFIG REQUIRED)
    else()
        find_package(ImWidgetV4 0.1.0 CONFIG REQUIRED PATHS "${IMWIDGETV4_SDK_DIR}" NO_DEFAULT_PATH)
    endif()
    get_property(IMWIDGETV4_SDK_IMPORTED_CONFIGURATIONS TARGET ImWidgetV4::core PROPERTY IMPORTED_CONFIGURATIONS)
    set(IMWIDGETV4_SDK_CONFIGURATIONS "")
    foreach(IMWIDGETV4_SDK_IMPORTED_CONFIGURATION IN LISTS IMWIDGETV4_SDK_IMPORTED_CONFIGURATIONS)
        string(TOLOWER "${IMWIDGETV4_SDK_IMPORTED_CONFIGURATION}" IMWIDGETV4_SDK_CONFIGURATION_LOWER)
        if(IMWIDGETV4_SDK_CONFIGURATION_LOWER STREQUAL "debug")
            list(APPEND IMWIDGETV4_SDK_CONFIGURATIONS Debug)
        elseif(IMWIDGETV4_SDK_CONFIGURATION_LOWER STREQUAL "release")
            list(APPEND IMWIDGETV4_SDK_CONFIGURATIONS Release)
        elseif(IMWIDGETV4_SDK_CONFIGURATION_LOWER STREQUAL "relwithdebinfo")
            list(APPEND IMWIDGETV4_SDK_CONFIGURATIONS RelWithDebInfo)
        elseif(IMWIDGETV4_SDK_CONFIGURATION_LOWER STREQUAL "minsizerel")
            list(APPEND IMWIDGETV4_SDK_CONFIGURATIONS MinSizeRel)
        else()
            list(APPEND IMWIDGETV4_SDK_CONFIGURATIONS "${IMWIDGETV4_SDK_IMPORTED_CONFIGURATION}")
        endif()
    endforeach()
    if(IMWIDGETV4_SDK_CONFIGURATIONS)
        list(REMOVE_DUPLICATES IMWIDGETV4_SDK_CONFIGURATIONS)
        if(CMAKE_CONFIGURATION_TYPES)
            set(CMAKE_CONFIGURATION_TYPES "${IMWIDGETV4_SDK_CONFIGURATIONS}" CACHE STRING "Available ImWidgetV4 SDK configurations" FORCE)
        elseif(CMAKE_BUILD_TYPE AND NOT CMAKE_BUILD_TYPE IN_LIST IMWIDGETV4_SDK_CONFIGURATIONS)
            message(FATAL_ERROR "The selected ImWidgetV4 SDK does not provide configuration '${CMAKE_BUILD_TYPE}'. Available configurations: ${IMWIDGETV4_SDK_CONFIGURATIONS}")
        endif()
    endif()
else()
    if(IMWIDGETV4_ROOT STREQUAL "")
        get_filename_component(IMWIDGETV4_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../ImWidgetV4" ABSOLUTE)
    endif()

    if(NOT EXISTS "${IMWIDGETV4_ROOT}/CMakeLists.txt")
        message(FATAL_ERROR "IMWIDGETV4_ROOT must point to the ImWidgetV4 library root.")
    endif()

set(IMWIDGETV4_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(IMWIDGETV4_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(IMWIDGETV4_BUILD_EDITOR OFF CACHE BOOL "" FORCE)
if(WIN32)
    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND ON CACHE BOOL "" FORCE)
    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND OFF CACHE BOOL "" FORCE)
elseif(ANDROID)
    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND OFF CACHE BOOL "" FORCE)
    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND ON CACHE BOOL "" FORCE)
else()
    set(IMWIDGETV4_BUILD_WIN32_DX11_BACKEND OFF CACHE BOOL "" FORCE)
    set(IMWIDGETV4_BUILD_ANDROID_GLES3_BACKEND OFF CACHE BOOL "" FORCE)
endif()

    add_subdirectory("${IMWIDGETV4_ROOT}" "${CMAKE_BINARY_DIR}/ImWidgetV4")
endif()

set(IMWIDGETV4_APP_SOURCES
    src/main.cpp
    generated/AppProjectConfig.cpp
    generated/MainView.cpp
    generated/TitleBarView.cpp
)

if(WIN32 AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/generated/AppResources.rc")
    list(APPEND IMWIDGETV4_APP_SOURCES generated/AppResources.rc)
endif()

if(ANDROID)
    set(IMWIDGETV4_ANDROID_NDK_ROOT "")
    if(DEFINED CMAKE_ANDROID_NDK)
        set(IMWIDGETV4_ANDROID_NDK_ROOT ${CMAKE_ANDROID_NDK})
    elseif(DEFINED ANDROID_NDK)
        set(IMWIDGETV4_ANDROID_NDK_ROOT ${ANDROID_NDK})
    endif()

    set(IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE "")
    if(IMWIDGETV4_ANDROID_NDK_ROOT)
        set(IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE
            ${IMWIDGETV4_ANDROID_NDK_ROOT}/sources/android/native_app_glue/android_native_app_glue.c
        )
    endif()

    add_library(${PROJECT_NAME} SHARED
        ${IMWIDGETV4_APP_SOURCES}
        ${IMWIDGETV4_ANDROID_NATIVE_APP_GLUE_SOURCE}
    )
else()
    add_executable(${PROJECT_NAME}
        ${IMWIDGETV4_APP_SOURCES}
    )
endif()

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/generated
)

if(IMWIDGETV4_LIBRARY_MODE STREQUAL "SDK" AND COMMAND imwidgetv4_attach_sdk_sources)
    imwidgetv4_attach_sdk_sources(${PROJECT_NAME})
endif()

target_link_libraries(${PROJECT_NAME} PRIVATE
    $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::core,imwidgetv4_core>
    $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::reflection_json,imwidgetv4_reflection_json>
)

if(WIN32)
    target_link_libraries(${PROJECT_NAME} PRIVATE
        $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::platform_win32_dx11,imwidgetv4_platform_win32_dx11>
        $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::app_host_win32_main,imwidgetv4_app_host_win32_main>
    )
    set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE TRUE)
elseif(ANDROID)
    target_link_libraries(${PROJECT_NAME} PRIVATE
        $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::platform_android_gles3,imwidgetv4_platform_android_gles3>
        $<IF:$<STREQUAL:${IMWIDGETV4_LIBRARY_MODE},SDK>,ImWidgetV4::app_host_android_main,imwidgetv4_app_host_android_main>
        android
        log
    )
    if(IMWIDGETV4_ANDROID_NDK_ROOT)
        target_include_directories(${PROJECT_NAME} PRIVATE
            ${IMWIDGETV4_ANDROID_NDK_ROOT}/sources/android/native_app_glue
        )
    endif()
else()
    message(FATAL_ERROR "Generated project supports only WIN32 or ANDROID hosts.")
endif()

if(MSVC)
    target_compile_options(${PROJECT_NAME} PRIVATE /utf-8)
endif()
