# ImWidgetV4 sample targets

if(TARGET imwidgetv4_platform_win32_dx11)
    add_subdirectory(ButtonDemo)
    add_subdirectory(BoxPanelDemo)
    add_subdirectory(CanvasPanelDemo)
    add_subdirectory(DragDropDemo)
    add_subdirectory(ExpandableBoxDemo)
    add_subdirectory(ImageDemo)
    add_subdirectory(InputWidgetsDemo)
    add_subdirectory(ListViewDemo)
    add_subdirectory(OutlineViewDemo)
    add_subdirectory(ReflectionInspectorDemo)
    add_subdirectory(ScrollBoxDemo)
    add_subdirectory(SplitterDemo)
    add_subdirectory(TabViewDemo)
    add_subdirectory(TextListDemo)
    add_subdirectory(UserWidgetDemo)
    add_subdirectory(WindowDemo)
endif()

if(TARGET imwidgetv4_platform_android_gles3)
    add_subdirectory(AndroidDemo)
endif()
